### ISSUE TITLE
Wording Error - replace "then" with "than"

### ISSUE THREAD

**Issue by evamizer** [learn-co-curriculum/dsc-knn-intro#1]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ X] Other (explain below)

### Source

```
" In the K-means algorithm, K represents the number of clusters rather **_then_** the number of neighbors. Unlike KNN, K-means is an iterative algorithm which repeats until convergence" 

"Then" should be than. 
```

### Concern

Grammer 

## (Optional) Proposed Solution

Just replace the word

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by christine-egan42** [comment]
corrected with commit #[6af245c](https://github.com/learn-co-curriculum/dsc-knn-intro/commit/6af245c707a50523498aca1ab97b7cfd750fe1c9)
